use crate::rom::{ExCode, ExCodeBug, ExCodeEffect};

#[rustfmt::skip]
pub static EX_CODES: &[ExCode] = &[
    ExCode { code: 0x1e, effect: ExCodeEffect::MaxHP(100),     bug: None },
    ExCode { code: 0x1f, effect: ExCodeEffect::MaxHP(150),     bug: None },
    ExCode { code: 0x20, effect: ExCodeEffect::MaxHP(200),     bug: None },
    ExCode { code: 0x21, effect: ExCodeEffect::MaxHP(250),     bug: None },
    ExCode { code: 0x22, effect: ExCodeEffect::MaxHP(300),     bug: None },
    ExCode { code: 0x23, effect: ExCodeEffect::MaxHP(350),     bug: None },
    ExCode { code: 0x24, effect: ExCodeEffect::MaxHP(400),     bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x25, effect: ExCodeEffect::MaxHP(450),     bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x26, effect: ExCodeEffect::MaxHP(500),     bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x27, effect: ExCodeEffect::MaxHP(550),     bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x28, effect: ExCodeEffect::MaxHP(600),     bug: Some(ExCodeBug::Custom(2)) },
    ExCode { code: 0x29, effect: ExCodeEffect::MaxHP(650),     bug: Some(ExCodeBug::Custom(2)) },
    ExCode { code: 0x2a, effect: ExCodeEffect::MaxHP(700),     bug: Some(ExCodeBug::Custom(2)) },
    ExCode { code: 0x2b, effect: ExCodeEffect::SuperArmor,     bug: None },
    ExCode { code: 0x2c, effect: ExCodeEffect::BreakBuster,    bug: Some(ExCodeBug::Custom(2)) },
    ExCode { code: 0x2d, effect: ExCodeEffect::BreakCharge,    bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x2e, effect: ExCodeEffect::ShadowShoes,    bug: None },
    ExCode { code: 0x2f, effect: ExCodeEffect::FloatShoes,     bug: None },
    ExCode { code: 0x30, effect: ExCodeEffect::AirShoes,       bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x31, effect: ExCodeEffect::UnderShirt,     bug: None },
    ExCode { code: 0x32, effect: ExCodeEffect::Block,          bug: None },
    ExCode { code: 0x33, effect: ExCodeEffect::Shield,         bug: None },
    ExCode { code: 0x34, effect: ExCodeEffect::Reflect,        bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x35, effect: ExCodeEffect::AntiDamage,     bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x36, effect: ExCodeEffect::MegaFolder(1),  bug: None },
    ExCode { code: 0x37, effect: ExCodeEffect::MegaFolder(2),  bug: Some(ExCodeBug::Custom(1)) },
    ExCode { code: 0x38, effect: ExCodeEffect::FastGauge,      bug: Some(ExCodeBug::Custom(2)) },
    ExCode { code: 0x39, effect: ExCodeEffect::SneakRun,       bug: None },
    ExCode { code: 0x3a, effect: ExCodeEffect::Humor,          bug: None },
    ExCode { code: 0x3b, effect: ExCodeEffect::MaxHP(800),     bug: Some(ExCodeBug::PoisonPanelStep) },
    ExCode { code: 0x3c, effect: ExCodeEffect::MaxHP(900),     bug: Some(ExCodeBug::PoisonPanelStep) },
    ExCode { code: 0x3d, effect: ExCodeEffect::MaxHP(1000),    bug: Some(ExCodeBug::PoisonPanelStep) },
    ExCode { code: 0x3e, effect: ExCodeEffect::MegaFolder(3),  bug: Some(ExCodeBug::PoisonPanelStep) },
    ExCode { code: 0x3f, effect: ExCodeEffect::MegaFolder(4),  bug: Some(ExCodeBug::PoisonPanelStep) },
    ExCode { code: 0x40, effect: ExCodeEffect::MegaFolder(5),  bug: Some(ExCodeBug::PoisonPanelStep) },
    ExCode { code: 0x41, effect: ExCodeEffect::GigaFolder(1),  bug: Some(ExCodeBug::PoisonPanelStep) },
];
