use serde::{Deserialize, Serialize};

// winit changed variant names, so we manage our own for backwards compatibility
#[derive(Debug, Hash, Ord, PartialOrd, PartialEq, Eq, Clone, Copy, Serialize, Deserialize)]
pub(crate) enum Key {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    Scroll,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    /// The Backspace key, right over Enter.
    Back,
    /// The Enter key.
    Return,
    /// The space bar.
    Space,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,

    Apostrophe,
    Apps,
    Backslash,
    Calculator,
    Capital,
    Comma,
    Convert,
    Equals,
    Grave,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Context,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    MyComputer,
    NextTrack,
    NoConvert,
    Period,
    PlayPause,
    Plus,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Tab,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Eject,
    IntlBackslash,
    Ro,
    Yen,
}

impl Key {
    pub fn resolve(winit_key: winit::keyboard::KeyCode) -> Option<Self> {
        let key = match winit_key {
            winit::keyboard::KeyCode::Backquote => Key::Grave,
            winit::keyboard::KeyCode::Backslash => Key::Backslash,
            winit::keyboard::KeyCode::BracketLeft => Key::LBracket,
            winit::keyboard::KeyCode::BracketRight => Key::RBracket,
            winit::keyboard::KeyCode::Comma => Key::Comma,
            winit::keyboard::KeyCode::Digit0 => Key::Key0,
            winit::keyboard::KeyCode::Digit1 => Key::Key1,
            winit::keyboard::KeyCode::Digit2 => Key::Key2,
            winit::keyboard::KeyCode::Digit3 => Key::Key3,
            winit::keyboard::KeyCode::Digit4 => Key::Key4,
            winit::keyboard::KeyCode::Digit5 => Key::Key5,
            winit::keyboard::KeyCode::Digit6 => Key::Key6,
            winit::keyboard::KeyCode::Digit7 => Key::Key7,
            winit::keyboard::KeyCode::Digit8 => Key::Key8,
            winit::keyboard::KeyCode::Digit9 => Key::Key9,
            winit::keyboard::KeyCode::Equal => Key::Equals,
            winit::keyboard::KeyCode::IntlBackslash => Key::IntlBackslash,
            winit::keyboard::KeyCode::IntlRo => Key::Ro,
            winit::keyboard::KeyCode::IntlYen => Key::Yen,
            winit::keyboard::KeyCode::KeyA => Key::A,
            winit::keyboard::KeyCode::KeyB => Key::B,
            winit::keyboard::KeyCode::KeyC => Key::C,
            winit::keyboard::KeyCode::KeyD => Key::D,
            winit::keyboard::KeyCode::KeyE => Key::E,
            winit::keyboard::KeyCode::KeyF => Key::F,
            winit::keyboard::KeyCode::KeyG => Key::G,
            winit::keyboard::KeyCode::KeyH => Key::H,
            winit::keyboard::KeyCode::KeyI => Key::I,
            winit::keyboard::KeyCode::KeyJ => Key::J,
            winit::keyboard::KeyCode::KeyK => Key::K,
            winit::keyboard::KeyCode::KeyL => Key::L,
            winit::keyboard::KeyCode::KeyM => Key::M,
            winit::keyboard::KeyCode::KeyN => Key::N,
            winit::keyboard::KeyCode::KeyO => Key::O,
            winit::keyboard::KeyCode::KeyP => Key::P,
            winit::keyboard::KeyCode::KeyQ => Key::Q,
            winit::keyboard::KeyCode::KeyR => Key::R,
            winit::keyboard::KeyCode::KeyS => Key::S,
            winit::keyboard::KeyCode::KeyT => Key::T,
            winit::keyboard::KeyCode::KeyU => Key::U,
            winit::keyboard::KeyCode::KeyV => Key::V,
            winit::keyboard::KeyCode::KeyW => Key::W,
            winit::keyboard::KeyCode::KeyX => Key::X,
            winit::keyboard::KeyCode::KeyY => Key::Y,
            winit::keyboard::KeyCode::KeyZ => Key::Z,
            winit::keyboard::KeyCode::Minus => Key::Minus,
            winit::keyboard::KeyCode::Period => Key::Period,
            winit::keyboard::KeyCode::Quote => Key::Apostrophe,
            winit::keyboard::KeyCode::Semicolon => Key::Semicolon,
            winit::keyboard::KeyCode::Slash => Key::Slash,
            winit::keyboard::KeyCode::AltLeft => Key::LAlt,
            winit::keyboard::KeyCode::AltRight => Key::RAlt,
            winit::keyboard::KeyCode::Backspace => Key::Back,
            winit::keyboard::KeyCode::CapsLock => Key::Capital,
            winit::keyboard::KeyCode::ContextMenu => Key::Context,
            winit::keyboard::KeyCode::ControlLeft => Key::LControl,
            winit::keyboard::KeyCode::ControlRight => Key::RControl,
            winit::keyboard::KeyCode::Enter => Key::Return,
            winit::keyboard::KeyCode::SuperLeft => Key::LWin,
            winit::keyboard::KeyCode::SuperRight => Key::RWin,
            winit::keyboard::KeyCode::ShiftLeft => Key::LShift,
            winit::keyboard::KeyCode::ShiftRight => Key::RShift,
            winit::keyboard::KeyCode::Space => Key::Space,
            winit::keyboard::KeyCode::Tab => Key::Tab,
            winit::keyboard::KeyCode::Convert => Key::Convert,
            winit::keyboard::KeyCode::NonConvert => Key::NoConvert,
            winit::keyboard::KeyCode::Delete => Key::Delete,
            winit::keyboard::KeyCode::End => Key::End,
            winit::keyboard::KeyCode::Home => Key::Home,
            winit::keyboard::KeyCode::Insert => Key::Insert,
            winit::keyboard::KeyCode::PageDown => Key::PageDown,
            winit::keyboard::KeyCode::PageUp => Key::PageUp,
            winit::keyboard::KeyCode::ArrowDown => Key::Down,
            winit::keyboard::KeyCode::ArrowLeft => Key::Left,
            winit::keyboard::KeyCode::ArrowRight => Key::Right,
            winit::keyboard::KeyCode::ArrowUp => Key::Up,
            winit::keyboard::KeyCode::NumLock => Key::Numlock,
            winit::keyboard::KeyCode::Numpad0 => Key::Numpad0,
            winit::keyboard::KeyCode::Numpad1 => Key::Numpad1,
            winit::keyboard::KeyCode::Numpad2 => Key::Numpad2,
            winit::keyboard::KeyCode::Numpad3 => Key::Numpad3,
            winit::keyboard::KeyCode::Numpad4 => Key::Numpad4,
            winit::keyboard::KeyCode::Numpad5 => Key::Numpad5,
            winit::keyboard::KeyCode::Numpad6 => Key::Numpad6,
            winit::keyboard::KeyCode::Numpad7 => Key::Numpad7,
            winit::keyboard::KeyCode::Numpad8 => Key::Numpad8,
            winit::keyboard::KeyCode::Numpad9 => Key::Numpad9,
            winit::keyboard::KeyCode::NumpadAdd => Key::NumpadAdd,
            winit::keyboard::KeyCode::NumpadComma => Key::NumpadComma,
            winit::keyboard::KeyCode::NumpadDecimal => Key::NumpadDecimal,
            winit::keyboard::KeyCode::NumpadDivide => Key::NumpadDivide,
            winit::keyboard::KeyCode::NumpadEnter => Key::NumpadEnter,
            winit::keyboard::KeyCode::NumpadEqual => Key::NumpadEquals,
            winit::keyboard::KeyCode::NumpadMultiply => Key::NumpadMultiply,
            winit::keyboard::KeyCode::NumpadStar => Key::NumpadMultiply,
            winit::keyboard::KeyCode::NumpadSubtract => Key::NumpadSubtract,
            winit::keyboard::KeyCode::Escape => Key::Escape,
            winit::keyboard::KeyCode::PrintScreen => Key::Snapshot,
            winit::keyboard::KeyCode::ScrollLock => Key::Scroll,
            winit::keyboard::KeyCode::Pause => Key::Pause,
            winit::keyboard::KeyCode::BrowserBack => Key::WebBack,
            winit::keyboard::KeyCode::BrowserFavorites => Key::WebFavorites,
            winit::keyboard::KeyCode::BrowserForward => Key::WebForward,
            winit::keyboard::KeyCode::BrowserHome => Key::WebHome,
            winit::keyboard::KeyCode::BrowserRefresh => Key::WebRefresh,
            winit::keyboard::KeyCode::BrowserSearch => Key::WebSearch,
            winit::keyboard::KeyCode::BrowserStop => Key::WebStop,
            winit::keyboard::KeyCode::Eject => Key::Eject,
            winit::keyboard::KeyCode::LaunchApp1 => Key::MyComputer,
            winit::keyboard::KeyCode::LaunchApp2 => Key::Calculator,
            winit::keyboard::KeyCode::LaunchMail => Key::Mail,
            winit::keyboard::KeyCode::MediaPlayPause => Key::PlayPause,
            winit::keyboard::KeyCode::MediaSelect => Key::MediaSelect,
            winit::keyboard::KeyCode::MediaStop => Key::MediaStop,
            winit::keyboard::KeyCode::MediaTrackNext => Key::NextTrack,
            winit::keyboard::KeyCode::MediaTrackPrevious => Key::PrevTrack,
            winit::keyboard::KeyCode::Meta => Key::LWin,
            winit::keyboard::KeyCode::F1 => Key::F1,
            winit::keyboard::KeyCode::F2 => Key::F2,
            winit::keyboard::KeyCode::F3 => Key::F3,
            winit::keyboard::KeyCode::F4 => Key::F4,
            winit::keyboard::KeyCode::F5 => Key::F5,
            winit::keyboard::KeyCode::F6 => Key::F6,
            winit::keyboard::KeyCode::F7 => Key::F7,
            winit::keyboard::KeyCode::F8 => Key::F8,
            winit::keyboard::KeyCode::F9 => Key::F9,
            winit::keyboard::KeyCode::F10 => Key::F10,
            winit::keyboard::KeyCode::F11 => Key::F11,
            winit::keyboard::KeyCode::F12 => Key::F12,
            winit::keyboard::KeyCode::F13 => Key::F13,
            winit::keyboard::KeyCode::F14 => Key::F14,
            winit::keyboard::KeyCode::F15 => Key::F15,
            winit::keyboard::KeyCode::F16 => Key::F16,
            winit::keyboard::KeyCode::F17 => Key::F17,
            winit::keyboard::KeyCode::F18 => Key::F18,
            winit::keyboard::KeyCode::F19 => Key::F19,
            winit::keyboard::KeyCode::F20 => Key::F20,
            winit::keyboard::KeyCode::F21 => Key::F21,
            winit::keyboard::KeyCode::F22 => Key::F22,
            winit::keyboard::KeyCode::F23 => Key::F23,
            winit::keyboard::KeyCode::F24 => Key::F24,
            winit::keyboard::KeyCode::F25 => Key::F25,
            winit::keyboard::KeyCode::F26 => Key::F26,
            winit::keyboard::KeyCode::F27 => Key::F27,
            winit::keyboard::KeyCode::F28 => Key::F28,
            winit::keyboard::KeyCode::F29 => Key::F29,
            winit::keyboard::KeyCode::F30 => Key::F30,
            winit::keyboard::KeyCode::F31 => Key::F31,
            winit::keyboard::KeyCode::F32 => Key::F32,
            winit::keyboard::KeyCode::F33 => Key::F33,
            winit::keyboard::KeyCode::F34 => Key::F34,
            winit::keyboard::KeyCode::F35 => Key::F35,
            _ => return None,
        };

        Some(key)
    }
}
