// THIS FILE IS GENERATED BY generate_ts_defs. DO NOT EDIT IT BY HAND!
export type Keymapping={"up":string;"down":string;"left":string;"right":string;"a":string;"b":string;"l":string;"r":string;"select":string;"start":string;};
export type U32=number;
export type U16=number;
export type ICEServer={"urls":(string)[];"username":string;"credential":string;};
export type MatchSettings={"session_id":string;"input_delay":U32;"match_type":U16;"replays_path":string;"replay_metadata":string;"matchmaking_connect_addr":string;"ice_servers":(ICEServer)[];};
export type Args={"window_title":string;"rom_path":string;"save_path":string;"keymapping":Keymapping;"match_settings":(MatchSettings|null);};
export type State=("Running"|"Waiting"|"Connecting");
export type Notification={"State":State;};
