name = "tango-signaling-server"
main = "src/index.ts"
compatibility_date = "2026-05-11"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "802d9ab0923141a4a2329cb0e9b293d5"

[[durable_objects.bindings]]
name = "MATCHMAKING"
class_name = "MatchmakingSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchmakingSession"]
