name = "tango-signaling-server"
main = "src/index.ts"
compatibility_date = "2026-05-11"

[[durable_objects.bindings]]
name = "MATCHMAKING"
class_name = "MatchmakingHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MatchmakingHub"]

[route]
pattern = "matchmaking.tango.n1gp.net"
zone_name = "n1gp.net"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false
