pub const PATCH_CARDS: &[Option<super::PatchCard4>; super::super::NUM_PATCH_CARD4S] = &[
    None,
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(100), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::MaxHP(100), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(150), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(150), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(200), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(200), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::MaxHP(250), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(250), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(300), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(300), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Aura(crate::rom::PatchCard4Aura::Barrier100), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::Blind), bugs: &[crate::rom::PatchCard4Bug::AutoMove] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::GrassPanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::PanelStep(crate::rom::PatchCard4Panel::Metal), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::PanelStep(crate::rom::PatchCard4Panel::Cracked), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::PanelStep(crate::rom::PatchCard4Panel::Broken), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::CustomSlots(2), bugs: &[crate::rom::PatchCard4Bug::CustomHP] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::MegaFolder(2), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BusterAttack(9), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::GutsMachineGun), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Cannon), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::MiniBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::HeatShot), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Bubbler), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Thunder1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Sword), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Spreader), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: crate::rom::PatchCard4Effect::PetMenu(crate::rom::PatchCard4PetColor::Blue), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: crate::rom::PatchCard4Effect::PetMenu(crate::rom::PatchCard4PetColor::Pink), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: crate::rom::PatchCard4Effect::PetMenu(crate::rom::PatchCard4PetColor::Green), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(350), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::MaxHP(350), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(400), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(400), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(450), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::MaxHP(450), bugs: &[crate::rom::PatchCard4Bug::Confused] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::MaxHP(500), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(500), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::AirShot), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::RandomTrapChip), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::BugBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::Crackout), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::CrackedPanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::PoisonPanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::FullSynchro, bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Aura(crate::rom::PatchCard4Aura::Barrier200), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::Guard1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::Crackout), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BusterAttack(14), bugs: &[crate::rom::PatchCard4Bug::HP(1), crate::rom::PatchCard4Bug::Confused] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::GigaFolder(1), bugs: &[crate::rom::PatchCard4Bug::CustomMinus1] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::CopyDamage), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WideShot1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Blizzard), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::HeatBreath), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::ElecShock), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WoodyPowder), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::PanelReturn), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WideSword), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Color(crate::rom::PatchCard4Color::Red), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Color(crate::rom::PatchCard4Color::Yellow), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(550), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::MaxHP(550), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::MaxHP(600), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(600), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::MaxHP(650), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(650), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(700), bugs: &[crate::rom::PatchCard4Bug::Confused] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::MegaEnergyBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::Recov10), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::PanelReturn), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::NorthWind), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::Lance), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::DoubleCrack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::TripleSupporter, bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::TripleSupporter, bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::AllGuard, bugs: &[crate::rom::PatchCard4Bug::HP(3)] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::AllGuard, bugs: &[crate::rom::PatchCard4Bug::HP(3)] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Aura(crate::rom::PatchCard4Aura::LifeAura), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Hole), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WideShot2), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::ZapRing), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::SandRing), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::EnergyBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Thunder2), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Repair), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::TripleCrack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::LongSword), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: crate::rom::PatchCard4Effect::PetMenu(crate::rom::PatchCard4PetColor::Black), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Color(crate::rom::PatchCard4Color::White), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::Color(crate::rom::PatchCard4Color::Green), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(700), bugs: &[crate::rom::PatchCard4Bug::PoisonPanelStep] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(750), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(750), bugs: &[crate::rom::PatchCard4Bug::HP(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(800), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(800), bugs: &[crate::rom::PatchCard4Bug::PoisonPanelStep] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::MaxHP(850), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(850), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::MaxHP(900), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(900), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 1, effect: crate::rom::PatchCard4Effect::MaxHP(950), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::MaxHP(1000), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::IcePanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::FullCustom), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::FullCustom), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::PanelStep(crate::rom::PatchCard4Panel::Holy), bugs: &[crate::rom::PatchCard4Bug::HP(1), crate::rom::PatchCard4Bug::CustomHP] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::Reflect), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::Flower), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::WaterGun), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: crate::rom::PatchCard4Effect::MegaFolder(3), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::CustomSlots(3), bugs: &[crate::rom::PatchCard4Bug::CustomHP] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::GigaFolder(1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: crate::rom::PatchCard4Effect::BLeft(crate::rom::PatchCard4Shot::TripleCrack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WideShot3), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Thunder3), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WindRack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::MegaEnergyBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::Ball), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::BugBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::WideBlade), bugs: &[crate::rom::PatchCard4Bug::AutoMove] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::BCharge(crate::rom::PatchCard4Shot::LongBlade), bugs: &[crate::rom::PatchCard4Bug::AutoMove] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Roll), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Guts), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Wind), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Search), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Fire), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Thunder), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Proto), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Number), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Metal), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Junk), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Aqua), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: crate::rom::PatchCard4Effect::Soul(crate::rom::PatchCard4Soul::Wood), bugs: &[crate::rom::PatchCard4Bug::HP(2)] }),
    Some(super::PatchCard4 { slot: 0, effect: crate::rom::PatchCard4Effect::BButton(crate::rom::PatchCard4Shot::MiniBomb), bugs: &[] }),
];

pub const JA_NAMES: &[&str; super::super::NUM_PATCH_CARD4S] = &[
    "",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "ファーストバリア100",
    "バスターを改造",
    "バスターを改造",
    "パネルチェンジ",
    "パネルチェンジ",
    "パネルチェンジ",
    "カスタム2",
    "メガフォルダ2",
    "バスター攻撃力10",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "PET画面カラー変更",
    "PET画面カラー変更",
    "PET画面カラー変更",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "バスターを改造",
    "バスターを改造",
    "デフォルトフルシンクロ",
    "ファーストバリア200",
    "ウェポンチェンジ",
    "ウェポンチェンジ",
    "バスター攻撃力15",
    "ギガフォルダ1",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "ロックマンカラーを変更",
    "ロックマンカラーを変更",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "トリプルサポーター1/2",
    "トリプルサポーター2/2",
    "オールガード1/2",
    "オールガード1/2",
    "ファーストドリームオーラ",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "PET画面カラー変更",
    "ロックマンカラーを変更",
    "ロックマンカラーを変更",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "バスターを改造",
    "チャージフルカスタム1/2",
    "チャージフルカスタム2/2",
    "パネルチェンジ",
    "ウェポンチェンジ",
    "ウェポンチェンジ",
    "ウェポンチェンジ",
    "メガフォルダ3",
    "カスタム3",
    "ギガフォルダ1",
    "B+左で技発動",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "ロールソウル",
    "ガッツソウル",
    "ウインドソウル",
    "サーチソウル",
    "ファイアソウル",
    "サンダーソウル",
    "ブルースソウル",
    "ナンバーソウル",
    "メタルソウル",
    "ジャンクソウル",
    "アクアソウル",
    "ウッドソウル",
    "ウェポンチェンジ",
];

pub const EN_NAMES: &[&str; super::super::NUM_PATCH_CARD4S] = &[
    "",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "First Barrier 100",
    "Buster Patch",
    "Buster Patch",
    "Panel Change",
    "Panel Change",
    "Panel Change",
    "Custom2",
    "MegaFolder2",
    "Buster Attack 10",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "PET Menu Color Change",
    "PET Menu Color Change",
    "PET Menu Color Change",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "Buster Patch",
    "Buster Patch",
    "Default Full Synchro",
    "First Barrier200",
    "Weapon Change",
    "Weapon Change",
    "Buster Attack 15",
    "GigaFolder1",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "MegaMan Color Change",
    "MegaMan Color Change",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "Triple Supporter 1/2",
    "Triple Supporter 2/2",
    "All Guard 1/2",
    "All Guard 2/2",
    "First Life Aura",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "PET Menu Color Change",
    "MegaMan Color Change",
    "MegaMan Color Change",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Buster Patch",
    "FullCustom Charge 1/2",
    "FullCustom Charge 2/2",
    "Panel Change",
    "Weapon Change",
    "Weapon Change",
    "Weapon Change",
    "MegaFolder3",
    "Custom3",
    "GigaFolder1",
    "B+Left Ability Activation",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Roll Soul",
    "Guts Soul",
    "Wind Soul",
    "Search Soul",
    "Fire Soul",
    "Thunder Soul",
    "Proto Soul",
    "Number Soul",
    "Metal Soul",
    "Junk Soul",
    "Aqua Soul",
    "Wood Soul",
    "Weapon Change",
];
