//! The Mod Card (patch card 4) model. BN4's cards are slot-addressed and
//! effect-typed in a way no other game shares, so the whole model lives
//! here — the shared dataview traits know nothing about it.

/// A BN4 patch-card (modcard) effect, reverse-engineered from the game's
/// effect jump table at `0x8041e8c`: each modcard id dispatches to a small
/// handler that calls `set_effect(id, param)` (`0x800d78a`). The variant
/// names the effect; a numeric payload is the raw game parameter (a chip /
/// soul / panel index, or an amount), so it stays faithful to the binary.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4Effect {
    /// No in-battle effect — the cosmetic PET-menu recolor cards.
    None,
    /// Max HP increased by this many points (direct `MaxHp += N`).
    MaxHp(u16),
    /// Buster attack power set to this level (`set_effect 0x05`).
    BusterAttack(u8),
    /// B Button shortcut / normal-shot modifier (`set_effect 0x09`).
    BButton(PatchCard4Shot),
    /// B + charge fires this chip (`set_effect 0x0a`).
    BCharge(PatchCard4Shot),
    /// B + ← fires this chip (`set_effect 0x0c`).
    BLeft(PatchCard4Shot),
    /// +N Custom-screen slots, capped at 8 (`set_effect 0x12`).
    CustomSlots(u8),
    /// +N Mega-chip folder limit, capped at 10 (`set_effect 0x13`).
    MegaFolder(u8),
    /// +N Giga-chip folder limit, capped at 10 (`set_effect 0x14`).
    GigaFolder(u8),
    /// Triple Supporter — needs both the 1/2 and 2/2 cards (`set_effect 0x18`).
    TripleSupporter,
    /// Stepping off a panel leaves this terrain (`set_effect 0x1b`).
    PanelStep(PatchCard4Panel),
    /// Start the battle in Full Synchro (`set_effect 0x1f`).
    FullSynchro,
    /// Start the battle with this aura / barrier (`set_effect 0x21`).
    Aura(PatchCard4Aura),
    /// Start the battle in this Soul Unison (`set_effect 0x24`).
    Soul(PatchCard4Soul),
    /// MegaMan recolor (`set_effect 0x27`).
    Color(PatchCard4Color),
    /// All Guard — needs both the 1/2 and 2/2 cards (`set_effect 0x28`).
    AllGuard,
    /// Recolors the overworld PET menu — a non-battle cosmetic, so the
    /// modcard's battle handler is empty (no `set_effect`); the colour is
    /// taken from the card.
    PetMenu(PatchCard4PetColor),
}

/// Terrain laid by a [`PatchCard4Effect::PanelStep`] card (`set_effect 0x1b`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4Panel {
    Broken,  // 1
    Cracked, // 3
    Metal,   // 5
    Holy,    // 9
}

/// Battle-start aura from a [`PatchCard4Effect::Aura`] card (`set_effect 0x21`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4Aura {
    Barrier100, // 2
    Barrier200, // 3
    LifeAura,   // 6
}

/// Soul Unison from a [`PatchCard4Effect::Soul`] card (`set_effect 0x24`, 1-based).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4Soul {
    Roll,
    Guts,
    Wind,
    Search,
    Fire,
    Thunder,
    Proto,
    Number,
    Metal,
    Junk,
    Aqua,
    Wood,
}

/// MegaMan recolor from a [`PatchCard4Effect::Color`] card (`set_effect 0x27`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4Color {
    Red,    // 1
    Yellow, // 2
    White,  // 3
    Green,  // 4
}

/// PET-menu colour from a [`PatchCard4Effect::PetMenu`] card.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4PetColor {
    Blue,
    Pink,
    Green,
    Black,
}

/// The chip/shot a [`PatchCard4Effect::BButton`]/[`BCharge`](PatchCard4Effect::BCharge)/
/// [`BLeft`](PatchCard4Effect::BLeft) card assigns. The discriminant is the
/// raw game param the modcard's `set_effect` writes (so `as u16` recovers it).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum PatchCard4Shot {
    ZapRing = 4,
    WaterGun = 32,
    Flower = 33,
    Reflect = 38,
    GutsMachineGun = 40,
    Cannon = 41,
    MiniBomb = 42,
    HeatShot = 43,
    Bubbler = 44,
    Thunder1 = 45,
    Sword = 46,
    Spreader = 47,
    RandomTrapChip = 49,
    CrackedPanel = 52,
    PoisonPanel = 53,
    Crackout = 54,
    CopyDamage = 55,
    WideShot1 = 56,
    Thunder2 = 58,
    DoubleCrack = 60,
    WideSword = 62,
    Recov10 = 64,
    Lance = 65,
    Hole = 66,
    WideShot2 = 67,
    SandRing = 68,
    EnergyBomb = 69,
    Thunder3 = 70,
    TripleCrack = 72,
    LongSword = 73,
    FullCustom = 75,
    WideShot3 = 76,
    WindRack = 78,
    MegaEnergyBomb = 79,
    Ball = 80,
    BugBomb = 81,
    WideBlade = 82,
    LongBlade = 83,
    NorthWind = 84,
    PanelReturn = 85,
    Blind = 90,
    Blizzard = 91,
    HeatBreath = 92,
    WoodyPowder = 93,
    Repair = 94,
    AirShot = 95,
    ElecShock = 96,
    Guard1 = 98,
    GrassPanel = 104,
    IcePanel = 105,
}

/// A BN4 patch-card drawback ("bug"), from `set_bug(category, param)`
/// (`0x80476e0`). A card can carry more than one.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PatchCard4Bug {
    /// Start the battle Confused (`set_bug 0x01, 1`).
    Confused,
    /// MegaMan auto-moves forward (`set_bug 0x01, 2`).
    AutoMove,
    /// HP drains during the battle (`set_bug 0x02, n`) — `n` is the severity.
    Hp(u8),
    /// Custom gauge HP bug (`set_bug 0x03, 1`).
    CustomHP,
    /// Custom gauge −1 (`set_bug 0x03, 2`).
    CustomMinus1,
    /// Poison panels appear as you step (`set_bug 0x04, 3`).
    PoisonPanelStep,
}

#[rustfmt::skip]
pub const PATCH_CARDS: &[Option<super::PatchCard4>; super::super::NUM_PATCH_CARD4S] = &[
    None,
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(100), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::MaxHp(100), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(150), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(150), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(200), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(200), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::MaxHp(250), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(250), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(300), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(300), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Aura(PatchCard4Aura::Barrier100), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::Blind), bugs: &[PatchCard4Bug::AutoMove] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::GrassPanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::PanelStep(PatchCard4Panel::Metal), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::PanelStep(PatchCard4Panel::Cracked), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::PanelStep(PatchCard4Panel::Broken), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::CustomSlots(2), bugs: &[PatchCard4Bug::CustomHP] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::MegaFolder(2), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BusterAttack(9), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::GutsMachineGun), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Cannon), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::MiniBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::HeatShot), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Bubbler), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Thunder1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Sword), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Spreader), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: PatchCard4Effect::PetMenu(PatchCard4PetColor::Blue), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: PatchCard4Effect::PetMenu(PatchCard4PetColor::Pink), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: PatchCard4Effect::PetMenu(PatchCard4PetColor::Green), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(350), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::MaxHp(350), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(400), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(400), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(450), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::MaxHp(450), bugs: &[PatchCard4Bug::Confused] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::MaxHp(500), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(500), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::AirShot), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::RandomTrapChip), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::BugBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::Crackout), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::CrackedPanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::PoisonPanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::FullSynchro, bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Aura(PatchCard4Aura::Barrier200), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::Guard1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::Crackout), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BusterAttack(14), bugs: &[PatchCard4Bug::Hp(1), PatchCard4Bug::Confused] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::GigaFolder(1), bugs: &[PatchCard4Bug::CustomMinus1] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::CopyDamage), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WideShot1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Blizzard), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::HeatBreath), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::ElecShock), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WoodyPowder), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::PanelReturn), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WideSword), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Color(PatchCard4Color::Red), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Color(PatchCard4Color::Yellow), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(550), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::MaxHp(550), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::MaxHp(600), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(600), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::MaxHp(650), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(650), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(700), bugs: &[PatchCard4Bug::Confused] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::MegaEnergyBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::Recov10), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::PanelReturn), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::NorthWind), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::Lance), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::DoubleCrack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::TripleSupporter, bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::TripleSupporter, bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::AllGuard, bugs: &[PatchCard4Bug::Hp(3)] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::AllGuard, bugs: &[PatchCard4Bug::Hp(3)] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Aura(PatchCard4Aura::LifeAura), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Hole), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WideShot2), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::ZapRing), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::SandRing), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::EnergyBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Thunder2), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Repair), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::TripleCrack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::LongSword), bugs: &[] }),
    Some(super::PatchCard4 { slot: 5, effect: PatchCard4Effect::PetMenu(PatchCard4PetColor::Black), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Color(PatchCard4Color::White), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::Color(PatchCard4Color::Green), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(700), bugs: &[PatchCard4Bug::PoisonPanelStep] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(750), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(750), bugs: &[PatchCard4Bug::Hp(1)] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(800), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(800), bugs: &[PatchCard4Bug::PoisonPanelStep] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::MaxHp(850), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(850), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::MaxHp(900), bugs: &[] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(900), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 1, effect: PatchCard4Effect::MaxHp(950), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::MaxHp(1000), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::IcePanel), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BCharge(PatchCard4Shot::FullCustom), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::FullCustom), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::PanelStep(PatchCard4Panel::Holy), bugs: &[PatchCard4Bug::Hp(1), PatchCard4Bug::CustomHP] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::Reflect), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::Flower), bugs: &[] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::WaterGun), bugs: &[] }),
    Some(super::PatchCard4 { slot: 2, effect: PatchCard4Effect::MegaFolder(3), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::CustomSlots(3), bugs: &[PatchCard4Bug::CustomHP] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::GigaFolder(1), bugs: &[] }),
    Some(super::PatchCard4 { slot: 3, effect: PatchCard4Effect::BLeft(PatchCard4Shot::TripleCrack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WideShot3), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Thunder3), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WindRack), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::MegaEnergyBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::Ball), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::BugBomb), bugs: &[] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::WideBlade), bugs: &[PatchCard4Bug::AutoMove] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::BCharge(PatchCard4Shot::LongBlade), bugs: &[PatchCard4Bug::AutoMove] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Roll), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Guts), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Wind), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Search), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Fire), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Thunder), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Proto), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Number), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Metal), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Junk), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Aqua), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 4, effect: PatchCard4Effect::Soul(PatchCard4Soul::Wood), bugs: &[PatchCard4Bug::Hp(2)] }),
    Some(super::PatchCard4 { slot: 0, effect: PatchCard4Effect::BButton(PatchCard4Shot::MiniBomb), bugs: &[] }),
];

pub const JA_NAMES: &[&str; super::super::NUM_PATCH_CARD4S] = &[
    "",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "ファーストバリア100",
    "バスターを改造",
    "バスターを改造",
    "パネルチェンジ",
    "パネルチェンジ",
    "パネルチェンジ",
    "カスタム2",
    "メガフォルダ2",
    "バスター攻撃力10",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "PET画面カラー変更",
    "PET画面カラー変更",
    "PET画面カラー変更",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "バスターを改造",
    "バスターを改造",
    "デフォルトフルシンクロ",
    "ファーストバリア200",
    "ウェポンチェンジ",
    "ウェポンチェンジ",
    "バスター攻撃力15",
    "ギガフォルダ1",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "ロックマンカラーを変更",
    "ロックマンカラーを変更",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "B+左で技発動",
    "トリプルサポーター1/2",
    "トリプルサポーター2/2",
    "オールガード1/2",
    "オールガード1/2",
    "ファーストドリームオーラ",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "PET画面カラー変更",
    "ロックマンカラーを変更",
    "ロックマンカラーを変更",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "マックスHPを強化",
    "バスターを改造",
    "チャージフルカスタム1/2",
    "チャージフルカスタム2/2",
    "パネルチェンジ",
    "ウェポンチェンジ",
    "ウェポンチェンジ",
    "ウェポンチェンジ",
    "メガフォルダ3",
    "カスタム3",
    "ギガフォルダ1",
    "B+左で技発動",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "チャージ武器を変更",
    "ロールソウル",
    "ガッツソウル",
    "ウインドソウル",
    "サーチソウル",
    "ファイアソウル",
    "サンダーソウル",
    "ブルースソウル",
    "ナンバーソウル",
    "メタルソウル",
    "ジャンクソウル",
    "アクアソウル",
    "ウッドソウル",
    "ウェポンチェンジ",
];

pub const EN_NAMES: &[&str; super::super::NUM_PATCH_CARD4S] = &[
    "",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "First Barrier 100",
    "Buster Patch",
    "Buster Patch",
    "Panel Change",
    "Panel Change",
    "Panel Change",
    "Custom2",
    "MegaFolder2",
    "Buster Attack 10",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "PET Menu Color Change",
    "PET Menu Color Change",
    "PET Menu Color Change",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "Buster Patch",
    "Buster Patch",
    "Default Full Synchro",
    "First Barrier200",
    "Weapon Change",
    "Weapon Change",
    "Buster Attack 15",
    "GigaFolder1",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "MegaMan Color Change",
    "MegaMan Color Change",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "B+Left Ability Activation",
    "Triple Supporter 1/2",
    "Triple Supporter 2/2",
    "All Guard 1/2",
    "All Guard 2/2",
    "First Life Aura",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "PET Menu Color Change",
    "MegaMan Color Change",
    "MegaMan Color Change",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Max HP Up",
    "Buster Patch",
    "FullCustom Charge 1/2",
    "FullCustom Charge 2/2",
    "Panel Change",
    "Weapon Change",
    "Weapon Change",
    "Weapon Change",
    "MegaFolder3",
    "Custom3",
    "GigaFolder1",
    "B+Left Ability Activation",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Charge Shot Switch",
    "Roll Soul",
    "Guts Soul",
    "Wind Soul",
    "Search Soul",
    "Fire Soul",
    "Thunder Soul",
    "Proto Soul",
    "Number Soul",
    "Metal Soul",
    "Junk Soul",
    "Aqua Soul",
    "Wood Soul",
    "Weapon Change",
];
